import { Router } from "express";
import { z } from "zod";
import { Quiz, QuizQuestion, LearningProgress, Course, Enrollment } from "../models";
import { authenticate, allowRoles } from "../middleware/auth";
import { asyncHandler, sendData, validateBody, HttpError, objectId } from "../utils/http";

const router = Router();
export const progressRouter = Router();
const quizSchema = z.object({ title: z.string().trim().min(3).max(160), description: z.string().max(2000).optional(), course: z.string().length(24).optional(), passingScore: z.coerce.number().min(0).max(100).default(60), published: z.boolean().default(false), questions: z.array(z.object({ prompt: z.string().trim().min(2).max(2000), options: z.array(z.string().max(500)).min(2).max(10), correctAnswer: z.number().int().min(0), explanation: z.string().max(2000).optional(), marks: z.coerce.number().min(1).max(100).default(1) })).min(1).max(100) }).superRefine((data, ctx) => data.questions.forEach((q, i) => { if (q.correctAnswer >= q.options.length) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["questions", i, "correctAnswer"], message: "Correct answer must select an existing option." }); }));
router.post("/", authenticate, allowRoles("creator", "admin"), validateBody(quizSchema), asyncHandler(async (req, res) => { const { questions, ...fields } = req.body as z.infer<typeof quizSchema>; if (fields.course) { const course = await Course.findById(fields.course); if (!course) throw new HttpError(404, "Course not found."); if (String(course.creator) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only add quizzes to your own course."); } const quiz = await Quiz.create({ ...fields, creator: req.user!.id }); const docs = await QuizQuestion.insertMany(questions.map((q) => ({ ...q, quiz: quiz._id }))); quiz.questions = docs.map((q) => q._id); await quiz.save(); sendData(res, { quiz, questions: docs }, "Quiz created.", 201); }));
router.get("/:id", asyncHandler(async (req, res) => { const quiz = await Quiz.findById(objectId(req.params.id)).populate("course", "title").populate("creator", "fullName"); if (!quiz || (!quiz.published && (!req.user || (String(quiz.creator?._id ?? quiz.creator) !== req.user.id && req.user.role !== "admin")))) throw new HttpError(404, "Quiz not found."); const questions = await QuizQuestion.find({ quiz: quiz._id }).select(req.user?.id === String(quiz.creator?._id ?? quiz.creator) || req.user?.role === "admin" ? "" : "-correctAnswer"); sendData(res, { quiz, questions }); }));
router.put("/:id", authenticate, allowRoles("creator", "admin"), validateBody(quizSchema.innerType().partial()), asyncHandler(async (req, res) => { const quiz = await Quiz.findById(objectId(req.params.id)); if (!quiz) throw new HttpError(404, "Quiz not found."); if (String(quiz.creator) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only edit your own quizzes."); const { questions, ...fields } = req.body as Partial<z.infer<typeof quizSchema>>; quiz.set(fields); if (questions) { await QuizQuestion.deleteMany({ quiz: quiz._id }); const docs = await QuizQuestion.insertMany(questions.map((q) => ({ ...q, quiz: quiz._id }))); quiz.questions = docs.map((q) => q._id); } await quiz.save(); sendData(res, quiz, "Quiz updated."); }));
router.delete("/:id", authenticate, allowRoles("creator", "admin"), asyncHandler(async (req, res) => { const quiz = await Quiz.findById(objectId(req.params.id)); if (!quiz) throw new HttpError(404, "Quiz not found."); if (String(quiz.creator) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only delete your own quizzes."); await Promise.all([QuizQuestion.deleteMany({ quiz: quiz._id }), quiz.deleteOne()]); sendData(res, {}, "Quiz deleted."); }));
router.post("/:id/submit", authenticate, validateBody(z.object({ answers: z.array(z.number().int().min(0)).max(100) })), asyncHandler(async (req, res) => { const quiz = await Quiz.findOne({ _id: objectId(req.params.id), published: true }); if (!quiz) throw new HttpError(404, "Quiz not found."); const questions = await QuizQuestion.find({ quiz: quiz._id }).sort({ createdAt: 1 }); const answers = (req.body as { answers: number[] }).answers; if (answers.length !== questions.length) throw new HttpError(400, "Submit one answer for every question."); const total = questions.reduce((sum, q) => sum + q.marks, 0); const earned = questions.reduce((sum, q, i) => sum + (answers[i] === q.correctAnswer ? q.marks : 0), 0); const score = total ? Math.round(earned / total * 100) : 0; const explanations = questions.map((q, i) => ({ questionId: q._id, prompt: q.prompt, selectedAnswer: answers[i], correctAnswer: q.correctAnswer, correct: answers[i] === q.correctAnswer, explanation: q.explanation, marksEarned: answers[i] === q.correctAnswer ? q.marks : 0 })); if (quiz.course) { await Enrollment.findOneAndUpdate({ user: req.user!.id, course: quiz.course }, { $setOnInsert: { status: "active" } }, { upsert: true }); await LearningProgress.findOneAndUpdate({ user: req.user!.id, course: quiz.course }, { $setOnInsert: { started: true }, $push: { quizAttempts: { quiz: quiz._id, score, takenAt: new Date(), passed: score >= quiz.passingScore } } }, { upsert: true, new: true }); } sendData(res, { score, totalMarks: total, earnedMarks: earned, passingScore: quiz.passingScore, passed: score >= quiz.passingScore, explanations }, "Quiz submitted."); }));

const progressSchema = z.object({ courseId: z.string().length(24), percentage: z.coerce.number().min(0).max(100).optional(), completed: z.boolean().optional(), lastWatchedLesson: z.string().length(24).optional(), completedLessons: z.array(z.string().length(24)).optional() });
progressRouter.post("/", authenticate, validateBody(progressSchema), asyncHandler(async (req, res) => { const body = req.body as z.infer<typeof progressSchema>; const courseId = objectId(body.courseId, "course id"); const course = await Course.findOne({ _id: courseId, published: true }); if (!course) throw new HttpError(404, "Course not found."); await Enrollment.updateOne({ user: req.user!.id, course: courseId }, { $setOnInsert: { user: req.user!.id, course: courseId } }, { upsert: true }); const progress = await LearningProgress.findOneAndUpdate({ user: req.user!.id, course: courseId }, { $set: { started: true, ...(body.percentage !== undefined && { percentage: body.percentage }), ...(body.completed !== undefined && { completed: body.completed }), ...(body.lastWatchedLesson && { lastWatchedLesson: objectId(body.lastWatchedLesson, "lesson id") }), ...(body.completedLessons && { completedLessons: body.completedLessons.map((x) => objectId(x, "lesson id")) }) } }, { new: true, upsert: true, runValidators: true }); if (progress.percentage >= 100 || progress.completed) { progress.completed = true; progress.percentage = 100; await progress.save(); await Enrollment.updateOne({ user: req.user!.id, course: courseId }, { status: "completed" }); } sendData(res, progress, "Learning progress saved."); }));
progressRouter.get("/:courseId", authenticate, asyncHandler(async (req, res) => { const courseId = objectId(req.params.courseId, "course id"); const progress = await LearningProgress.findOne({ user: req.user!.id, course: courseId }).populate("lastWatchedLesson"); sendData(res, progress || { started: false, percentage: 0, completed: false, completedLessons: [] }); }));
export default router;





