import { Router } from "express";
import { z } from "zod";
import { Course, CourseModule, Enrollment, LearningProgress, User, Category } from "../models";
import { authenticate, allowRoles } from "../middleware/auth";
import { asyncHandler, sendData, validateBody, HttpError, objectId } from "../utils/http";
import { notify } from "../utils/notify";

const router = Router();
const courseInput = z.object({ title: z.string().trim().min(3).max(160), description: z.string().trim().min(10).max(5000), category: z.string().optional(), subcategory: z.string().max(100).optional(), difficulty: z.enum(["beginner", "intermediate", "advanced"]).default("beginner"), thumbnail: z.string().url().optional().or(z.literal("")), tags: z.array(z.string().max(50)).max(30).default([]), objectives: z.array(z.string().max(250)).max(30).default([]), prerequisites: z.array(z.string().max(250)).max(30).default([]), duration: z.coerce.number().min(0).default(0), published: z.boolean().default(false), modules: z.array(z.object({ title: z.string().trim().min(1).max(160), description: z.string().max(1000).optional(), lessons: z.array(z.object({ title: z.string().trim().min(1).max(160), content: z.string().max(10000).optional(), video: z.string().length(24).optional(), duration: z.coerce.number().min(0).optional() })).default([]) })).max(100).optional() });
const filters = (query: Record<string, unknown>) => { const f: Record<string, unknown> = { published: true }; if (query.category) f.category = query.category; if (query.difficulty) f.difficulty = query.difficulty; if (query.rating) f.averageRating = { $gte: Math.min(5, Math.max(0, Number(query.rating) || 0)) }; if (query.q) { const q = String(query.q).slice(0, 100).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const rx = new RegExp(q, "i"); f.$or = [{ title: rx }, { description: rx }, { tags: rx }]; } return f; };
router.get("/", asyncHandler(async (req, res) => { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 12)); const rows = await Course.find(filters(req.query as Record<string, unknown>)).populate("creator", "fullName branch year").populate("category", "name slug").sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit); sendData(res, { items: rows, page, limit, total: await Course.countDocuments(filters(req.query as Record<string, unknown>)) }); }));
router.post("/", authenticate, allowRoles("creator", "admin"), validateBody(courseInput), asyncHandler(async (req, res) => { const input = req.body as z.infer<typeof courseInput>; if (input.category && !(await Category.exists({ _id: input.category }))) throw new HttpError(400, "Course category was not found."); const course = await Course.create({ ...input, creator: req.user!.id }); if (input.modules?.length) { const { Lesson } = await import("../models"); const modules = await Promise.all(input.modules.map(async (mod, index) => { const row = await CourseModule.create({ course: course._id, title: mod.title, description: mod.description, position: index }); await Lesson.insertMany(mod.lessons.map((lesson, position) => ({ ...lesson, module: row._id, position }))); return row; })); course.modules = modules.map((m) => m._id); await course.save(); } sendData(res, course, "Course created.", 201); }));
router.get("/:id", asyncHandler(async (req, res) => { const id = objectId(req.params.id); const course = await Course.findById(id).populate("creator", "fullName branch year").populate("category", "name slug").populate({ path: "modules", options: { sort: { position: 1 } } }); if (!course) throw new HttpError(404, "Course not found."); if (!course.published && (!req.user || (String(course.creator?._id ?? course.creator) !== req.user.id && req.user.role !== "admin"))) throw new HttpError(404, "Course not found."); const { Lesson } = await import("../models"); const modules = await Promise.all((course.modules as unknown as Array<{ _id: unknown }>).map(async (m) => ({ ...((m as unknown as Record<string, unknown>)), lessons: await Lesson.find({ module: m._id }).sort({ position: 1 }) }))); sendData(res, { course, modules }); }));
router.put("/:id", authenticate, allowRoles("creator", "admin"), validateBody(courseInput.partial()), asyncHandler(async (req, res) => { const course = await Course.findById(objectId(req.params.id)); if (!course) throw new HttpError(404, "Course not found."); if (String(course.creator) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only edit your own courses."); const input = req.body as Partial<z.infer<typeof courseInput>>; course.set(Object.fromEntries(Object.entries(input).filter(([key]) => key !== "modules"))); if (input.modules) { const old = await CourseModule.find({ course: course._id }); const { Lesson } = await import("../models"); await Lesson.deleteMany({ module: { $in: old.map((m) => m._id) } }); await CourseModule.deleteMany({ course: course._id }); const modules = await Promise.all(input.modules.map(async (mod, index) => { const row = await CourseModule.create({ course: course._id, title: mod.title, description: mod.description, position: index }); await Lesson.insertMany(mod.lessons.map((lesson, position) => ({ ...lesson, module: row._id, position }))); return row; })); course.modules = modules.map((m) => m._id); } await course.save(); if (course.published) { const users = await Enrollment.find({ course: course._id }).distinct("user"); await Promise.all(users.filter((id) => String(id) !== req.user!.id).map((id) => notify(String(id), "course_update", `A course you enrolled in was updated: ${course.title}`, `/courses/${course._id}`))); } sendData(res, course, "Course updated."); }));
router.delete("/:id", authenticate, allowRoles("creator", "admin"), asyncHandler(async (req, res) => { const course = await Course.findById(objectId(req.params.id)); if (!course) throw new HttpError(404, "Course not found."); if (String(course.creator) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only delete your own courses."); const modules = await CourseModule.find({ course: course._id }).distinct("_id"); const { Lesson, Quiz } = await import("../models"); await Promise.all([Lesson.deleteMany({ module: { $in: modules } }), CourseModule.deleteMany({ course: course._id }), Enrollment.deleteMany({ course: course._id }), LearningProgress.deleteMany({ course: course._id }), Quiz.deleteMany({ course: course._id }), Course.deleteOne({ _id: course._id })]); sendData(res, {}, "Course deleted."); }));
router.post("/:id/enroll", authenticate, asyncHandler(async (req, res) => { const id = objectId(req.params.id); const course = await Course.findOne({ _id: id, published: true }); if (!course) throw new HttpError(404, "Course not found."); let enrollment; let created = false; try { enrollment = await Enrollment.create({ user: req.user!.id, course: id }); created = true; } catch (err) { if ((err as { code?: number })?.code !== 11000) throw err; enrollment = await Enrollment.findOne({ user: req.user!.id, course: id }); if (!enrollment) throw err; } if (created) await Course.updateOne({ _id: id }, { $inc: { enrollmentCount: 1 } }); sendData(res, enrollment, created ? "Enrollment saved." : "You are already enrolled.", created ? 201 : 200); }));
router.get("/me/courses", authenticate, asyncHandler(async (req, res) => { const rows = await Enrollment.find({ user: req.user!.id }).populate({ path: "course", populate: [{ path: "creator", select: "fullName" }, { path: "category", select: "name" }] }).sort({ enrolledAt: -1 }); sendData(res, rows); }));
export default router;


