import { Router } from "express";
import { z } from "zod";
import { Comment, Rating, Review, Course, Video, Note, Connection, Conversation, Message, SavedContent, Notification, User, Report, CreatorApplication } from "../models";
import { authenticate, allowRoles } from "../middleware/auth";
import { asyncHandler, sendData, validateBody, HttpError, objectId } from "../utils/http";
import { notify } from "../utils/notify";
import { follow } from "./users";

const router = Router();
const types = { Course, Video, Note } as const;
type ContentType = keyof typeof types;
function contentModel(type: string): (typeof types)[ContentType] { if (!(type in types)) throw new HttpError(400, "contentType must be Course, Video, or Note."); return types[type as ContentType]; }
function cleanText(text: string): string { return text.replace(/<[^>]*>/g, "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "").trim(); }
function sanitized(schema: z.ZodTypeAny, field: string) { return (req: import("express").Request, res: import("express").Response, next: import("express").NextFunction) => { const v = schema.safeParse(req.body); if (!v.success) return next(new HttpError(400, v.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; "))); (v.data as Record<string, unknown>)[field] = cleanText(String((v.data as Record<string, unknown>)[field])); req.body = v.data; next(); }; }
const commentInput = z.object({ contentType: z.string().min(1).max(30), contentId: z.string().length(24), body: z.string().trim().min(1).max(2000) });
router.get("/comments", asyncHandler(async (req, res) => { const f: Record<string, unknown> = {}; if (req.query.contentType) f.contentType = String(req.query.contentType); if (req.query.contentId) f.content = objectId(String(req.query.contentId), "content id"); if (req.query.parent === "root") f.parent = null; const rows = await Comment.find(f).populate("user", "fullName role").sort({ createdAt: -1 }).limit(Math.min(100, Number(req.query.limit) || 50)); sendData(res, rows); }));
router.post("/comments", authenticate, sanitized(commentInput, "body"), asyncHandler(async (req, res) => { const b = req.body as z.infer<typeof commentInput>; const Model = contentModel(b.contentType); if (!(await Model.exists({ _id: objectId(b.contentId) }))) throw new HttpError(404, "Content not found."); const row = await Comment.create({ user: req.user!.id, contentType: b.contentType, content: b.contentId, body: b.body }); sendData(res, row, "Comment added.", 201); }));
router.post("/comments/:id/reply", authenticate, sanitized(z.object({ body: z.string().trim().min(1).max(2000) }), "body"), asyncHandler(async (req, res) => { const parent = await Comment.findById(objectId(req.params.id)); if (!parent) throw new HttpError(404, "Comment not found."); const row = await Comment.create({ user: req.user!.id, contentType: parent.contentType, content: parent.content, parent: parent._id, body: (req.body as {body:string}).body }); await notify(String(parent.user), "comment_reply", "Someone replied to your comment.", `/comments/${row._id}`); sendData(res, row, "Reply added.", 201); }));
router.put("/comments/:id", authenticate, sanitized(z.object({ body: z.string().trim().min(1).max(2000) }), "body"), asyncHandler(async (req, res) => { const row = await Comment.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Comment not found."); if (String(row.user) !== req.user!.id) throw new HttpError(403, "You can only edit your own comments."); row.body = (req.body as {body:string}).body; await row.save(); sendData(res, row, "Comment updated."); }));
router.delete("/comments/:id", authenticate, asyncHandler(async (req, res) => { const row = await Comment.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Comment not found."); if (String(row.user) !== req.user!.id && req.user!.role !== "admin") throw new HttpError(403, "You can only delete your own comments."); await Comment.deleteMany({ $or: [{ _id: row._id }, { parent: row._id }] }); sendData(res, {}, "Comment deleted."); }));
router.post("/comments/:id/like", authenticate, asyncHandler(async (req, res) => { const row = await Comment.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Comment not found."); const exists = row.likes.some((id: unknown) => String(id) === req.user!.id); if (exists) row.likes = row.likes.filter((id: unknown) => String(id) !== req.user!.id) as typeof row.likes; else { row.likes.push(req.user!.id as never); if (String(row.user) !== req.user!.id) await notify(String(row.user), "like", "Someone liked your comment.", `/comments/${row._id}`); } await row.save(); sendData(res, { liked: !exists, likes: row.likes.length }); }));
router.post("/comments/:id/report", authenticate, validateBody(z.object({ reason: z.enum(["spam", "misleading", "inappropriate", "copyright", "harassment", "wrong information", "other"]), details: z.string().max(2000).optional() })), asyncHandler(async (req, res) => { const row = await Comment.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Comment not found."); const body = req.body as {reason:string;details?:string}; const report = await Report.create({ reporter: req.user!.id, targetType: "Comment", target: row._id, reason: body.reason, details: body.details }); sendData(res, report, "Comment reported.", 201); }));

const ratingSchema = z.object({ contentType: z.enum(["Course", "Video", "Note"]), contentId: z.string().length(24), value: z.coerce.number().int().min(1).max(5) });
async function refreshRating(type: ContentType, content: string) { const Model = types[type]; const aggregate = await Rating.aggregate([{ $match: { contentType: type, content: new (await import("mongoose")).default.Types.ObjectId(content) } }, { $group: { _id: null, avg: { $avg: "$value" }, count: { $sum: 1 } } }]); await Model.updateOne({ _id: content }, { averageRating: aggregate[0]?.avg || 0, ratingCount: aggregate[0]?.count || 0 }); }
router.post("/ratings", authenticate, validateBody(ratingSchema), asyncHandler(async (req, res) => { const b = req.body as z.infer<typeof ratingSchema>; const Model = contentModel(b.contentType); if (!(await Model.exists({ _id: b.contentId }))) throw new HttpError(404, "Content not found."); const row = await Rating.create({ user: req.user!.id, contentType: b.contentType, content: b.contentId, value: b.value }).catch((e) => { if (e?.code === 11000) throw new HttpError(409, "You have already rated this content."); throw e; }); await refreshRating(b.contentType, b.contentId); sendData(res, row, "Rating added.", 201); }));
router.put("/ratings/:id", authenticate, validateBody(z.object({ value: z.coerce.number().int().min(1).max(5) })), asyncHandler(async (req, res) => { const row = await Rating.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Rating not found."); if (String(row.user) !== req.user!.id) throw new HttpError(403, "You can only edit your own rating."); row.value = (req.body as {value:number}).value; await row.save(); await refreshRating(row.contentType, String(row.content)); sendData(res, row, "Rating updated."); }));
router.get("/ratings/:contentId", asyncHandler(async (req, res) => { const content = objectId(req.params.contentId, "content id"); const type = req.query.contentType ? String(req.query.contentType) : undefined; const filter: Record<string, unknown> = { content }; if (type) filter.contentType = type; const aggregateFilter = { ...filter, content: new (await import("mongoose")).default.Types.ObjectId(content) }; const [rows, stats] = await Promise.all([Rating.find(filter).populate("user", "fullName").sort({ createdAt: -1 }).limit(100), Rating.aggregate([{ $match: aggregateFilter }, { $group: { _id: null, average: { $avg: "$value" }, count: { $sum: 1 } } }])]); sendData(res, { items: rows, average: stats[0]?.average || 0, count: stats[0]?.count || 0 }); }));
const reviewSchema = z.object({ contentType: z.enum(["Course", "Video", "Note"]), contentId: z.string().length(24), text: z.string().trim().min(3).max(2000), rating: z.coerce.number().int().min(1).max(5).optional() });
router.post("/reviews", authenticate, validateBody(reviewSchema), asyncHandler(async (req, res) => { const b = req.body as z.infer<typeof reviewSchema>; if (!(await contentModel(b.contentType).exists({ _id: b.contentId }))) throw new HttpError(404, "Content not found."); const exists = await Review.exists({ user: req.user!.id, contentType: b.contentType, content: b.contentId }); if (exists) throw new HttpError(409, "You have already reviewed this content."); const row = await Review.create({ ...b, content: b.contentId, user: req.user!.id }); const content = await contentModel(b.contentType).findById(b.contentId); if (content && String(content.creator) !== req.user!.id) await notify(String(content.creator), "review", "Someone reviewed your content.", `/content/${b.contentId}`); sendData(res, row, "Review added.", 201); }));
router.put("/reviews/:id", authenticate, validateBody(z.object({ text: z.string().trim().min(3).max(2000).optional(), rating: z.coerce.number().int().min(1).max(5).optional() })), asyncHandler(async (req, res) => { const row = await Review.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Review not found."); if (String(row.user) !== req.user!.id) throw new HttpError(403, "You can only edit your own reviews."); row.set(req.body); await row.save(); sendData(res, row, "Review updated."); }));
router.get("/reviews/:contentId", asyncHandler(async (req, res) => { const rows = await Review.find({ content: objectId(req.params.contentId, "content id") }).populate("user", "fullName").sort({ createdAt: -1 }).limit(100); sendData(res, rows); }));

router.post("/follow/:userId", authenticate, asyncHandler(async (req, res) => { await follow(req.user!.id, objectId(req.params.userId)); sendData(res, {}, "Followed.", 201); }));
router.delete("/follow/:userId", authenticate, asyncHandler(async (req, res) => { const { Follow } = await import("../models"); await Follow.deleteOne({ follower: req.user!.id, following: objectId(req.params.userId) }); sendData(res, {}, "Unfollowed."); }));
router.post("/connections/request", authenticate, validateBody(z.object({ recipientId: z.string().length(24) })), asyncHandler(async (req, res) => { const recipient = objectId((req.body as {recipientId:string}).recipientId); if (recipient === req.user!.id) throw new HttpError(400, "You cannot connect with yourself."); if (!(await User.exists({ _id: recipient, isActive: true }))) throw new HttpError(404, "User not found."); const existing = await (await import("../models")).Connection.findOne({ $or: [{ requester: req.user!.id, recipient }, { requester: recipient, recipient: req.user!.id }] }); if (existing) throw new HttpError(409, "A connection request already exists."); const row = await (await import("../models")).Connection.create({ requester: req.user!.id, recipient }); await notify(recipient, "connection_request", "You received a connection request.", `/connections/${row._id}`); sendData(res, row, "Connection request sent.", 201); }));
router.post("/connections/:id/accept", authenticate, asyncHandler(async (req, res) => { const { Connection } = await import("../models"); const row = await Connection.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Connection request not found."); if (String(row.recipient) !== req.user!.id) throw new HttpError(403, "Only the recipient can accept this request."); if (row.status !== "pending") throw new HttpError(409, "This request is no longer pending."); row.status = "accepted"; await row.save(); await notify(String(row.requester), "connection_accepted", "Your connection request was accepted.", `/users/${req.user!.id}`); sendData(res, row, "Connection accepted."); }));
router.post("/connections/:id/reject", authenticate, asyncHandler(async (req, res) => { const { Connection } = await import("../models"); const row = await Connection.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Connection request not found."); if (String(row.recipient) !== req.user!.id) throw new HttpError(403, "Only the recipient can reject this request."); row.status = "rejected"; await row.save(); sendData(res, row, "Connection rejected."); }));
router.delete("/connections/:id", authenticate, asyncHandler(async (req, res) => { const { Connection } = await import("../models"); const row = await Connection.findById(objectId(req.params.id)); if (!row) throw new HttpError(404, "Connection not found."); if (![String(row.requester), String(row.recipient)].includes(req.user!.id)) throw new HttpError(403, "You are not part of this connection."); await row.deleteOne(); sendData(res, {}, "Connection removed."); }));

router.get("/conversations", authenticate, asyncHandler(async (req, res) => { const rows = await Conversation.find({ participants: req.user!.id }).populate("participants", "fullName role").populate("lastMessage").sort({ updatedAt: -1 }); sendData(res, rows); }));
router.post("/conversations", authenticate, validateBody(z.object({ userId: z.string().length(24) })), asyncHandler(async (req, res) => { const other = objectId((req.body as {userId:string}).userId); if (other === req.user!.id) throw new HttpError(400, "You cannot start a conversation with yourself."); if (!(await User.exists({ _id: other, isActive: true }))) throw new HttpError(404, "User not found."); let row = await Conversation.findOne({ participants: { $all: [req.user!.id, other], $size: 2 } }); if (!row) row = await Conversation.create({ participants: [req.user!.id, other] }); sendData(res, row, "Conversation ready.", 201); }));
router.get("/conversations/:id/messages", authenticate, asyncHandler(async (req, res) => { const id = objectId(req.params.id); const conversation = await Conversation.findOne({ _id: id, participants: req.user!.id }); if (!conversation) throw new HttpError(404, "Conversation not found."); const rows = await Message.find({ conversation: id }).populate("sender", "fullName").sort({ createdAt: 1 }).limit(500); sendData(res, rows); }));
router.post("/conversations/:id/messages", authenticate, validateBody(z.object({ body: z.string().trim().min(1).max(5000) })), asyncHandler(async (req, res) => { const id = objectId(req.params.id); const conversation = await Conversation.findOne({ _id: id, participants: req.user!.id }); if (!conversation) throw new HttpError(404, "Conversation not found."); const body = cleanText((req.body as {body:string}).body); if (!body) throw new HttpError(400, "Message cannot be empty."); const message = await Message.create({ conversation: id, sender: req.user!.id, body, readBy: [req.user!.id] }); conversation.lastMessage = message._id; await conversation.save(); const recipient = conversation.participants.find((p: unknown) => String(p) !== req.user!.id); if (recipient) await notify(String(recipient), "message", "You received a message.", `/conversations/${id}`); sendData(res, message, "Message sent.", 201); }));
router.post("/messages/:id/read", authenticate, asyncHandler(async (req, res) => { const message = await Message.findById(objectId(req.params.id)); if (!message) throw new HttpError(404, "Message not found."); if (!(await Conversation.exists({ _id: message.conversation, participants: req.user!.id }))) throw new HttpError(403, "You cannot access this conversation."); await Message.updateOne({ _id: message._id }, { $addToSet: { readBy: req.user!.id } }); sendData(res, { read: true }, "Message marked read."); }));
router.post("/saved", authenticate, validateBody(z.object({ contentType: z.enum(["Course", "Video", "Note"]), contentId: z.string().length(24) })), asyncHandler(async (req, res) => { const b = req.body as {contentType:ContentType;contentId:string}; if (!(await contentModel(b.contentType).exists({ _id: b.contentId }))) throw new HttpError(404, "Content not found."); const row = await SavedContent.findOneAndUpdate({ user: req.user!.id, contentType: b.contentType, content: b.contentId }, { $setOnInsert: { user: req.user!.id, contentType: b.contentType, content: b.contentId } }, { new: true, upsert: true }); sendData(res, row, "Content saved.", 201); }));
router.get("/saved", authenticate, asyncHandler(async (req, res) => { const rows = await SavedContent.find({ user: req.user!.id }).sort({ createdAt: -1 }); const items = await Promise.all(rows.map(async (r) => ({ saved: r, content: await contentModel(r.contentType).findById(r.content).populate("creator", "fullName") }))); sendData(res, items); }));
router.delete("/saved/:id", authenticate, asyncHandler(async (req, res) => { const row = await SavedContent.findOneAndDelete({ _id: objectId(req.params.id), user: req.user!.id }); if (!row) throw new HttpError(404, "Saved item not found."); sendData(res, {}, "Saved item removed."); }));
router.get("/notifications", authenticate, asyncHandler(async (req, res) => { sendData(res, await Notification.find({ user: req.user!.id }).sort({ createdAt: -1 }).limit(100)); }));
router.post("/notifications/:id/read", authenticate, asyncHandler(async (req, res) => { const row = await Notification.findOneAndUpdate({ _id: objectId(req.params.id), user: req.user!.id }, { $set: { readAt: new Date() } }, { new: true }); if (!row) throw new HttpError(404, "Notification not found."); sendData(res, row, "Notification marked read."); }));
router.post("/creator/apply", authenticate, validateBody(z.object({ motivation: z.string().trim().min(30).max(2000), expertise: z.array(z.string().trim().min(1).max(80)).min(1).max(20) })), asyncHandler(async (req, res) => { if (req.user!.role !== "student") throw new HttpError(409, "Only students can apply to become creators."); const previous = await CreatorApplication.findOne({ user: req.user!.id, status: "pending" }); if (previous) throw new HttpError(409, "You already have a pending creator application."); const row = await CreatorApplication.create({ ...(req.body as object), user: req.user!.id }); sendData(res, row, "Creator application submitted.", 201); }));
router.get("/creator/application", authenticate, asyncHandler(async (req, res) => { sendData(res, await CreatorApplication.findOne({ user: req.user!.id }).sort({ createdAt: -1 })); }));
router.get("/creator/dashboard", authenticate, allowRoles("creator", "admin"), asyncHandler(async (req, res) => { const [courses, videos, notes] = await Promise.all([Course.find({ creator: req.user!.id }), Video.find({ creator: req.user!.id }), Note.find({ creator: req.user!.id })]); const courseIds = courses.map((c) => c._id); sendData(res, { counts: { courses: courses.length, videos: videos.length, notes: notes.length, enrollments: courses.reduce((sum, c) => sum + c.enrollmentCount, 0) }, courses, videos, notes }); }));
router.post("/reports", authenticate, validateBody(z.object({ targetType: z.enum(["Course", "Video", "Note", "Comment", "Review", "User"]), targetId: z.string().length(24), reason: z.enum(["spam", "misleading", "inappropriate", "copyright", "harassment", "wrong information", "other"]), details: z.string().max(2000).optional() })), asyncHandler(async (req, res) => { const b = req.body as {targetType:string;targetId:string;reason:string;details?:string}; const row = await Report.create({ reporter: req.user!.id, targetType: b.targetType, target: b.targetId, reason: b.reason, details: b.details }); sendData(res, row, "Report submitted.", 201); }));
export default router;
