import { Router } from "express";
import { z } from "zod";
import { User, Profile, Skill, UserSkill, Follow, Notification } from "../models";
import { authenticate, allowRoles } from "../middleware/auth";
import { asyncHandler, sendData, validateBody, HttpError, objectId } from "../utils/http";
import { notify } from "../utils/notify";

const router = Router();
const profileSchema = z.object({ fullName: z.string().trim().min(2).max(100).optional(), branch: z.string().trim().max(100).optional(), year: z.coerce.number().int().min(1).max(8).optional(), interests: z.array(z.string().trim().max(80)).max(30).optional(), bio: z.string().trim().max(500).optional(), avatar: z.string().url().optional().or(z.literal("")), location: z.string().max(120).optional(), socialLinks: z.record(z.string(), z.string().url()).optional() });
router.get("/", asyncHandler(async (req, res) => { const filter: Record<string, unknown> = { isActive: true }; if (req.query.role) filter.role = String(req.query.role); if (req.query.branch) filter.branch = String(req.query.branch); if (req.query.year) filter.year = Number(req.query.year); if (req.query.skill) { const escaped = String(req.query.skill).slice(0, 80).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); const skill = await Skill.findOne({ name: new RegExp(escaped, "i") }); const links = skill ? await UserSkill.find({ skill: skill._id, intent: "know" }).distinct("user") : []; filter._id = { $in: links }; } const users = await User.find(filter).select("fullName role branch year interests createdAt").limit(Math.min(Number(req.query.limit) || 25, 100)); sendData(res, users); }));
router.get("/:id", asyncHandler(async (req, res) => { const id = objectId(req.params.id); const user = await User.findOne({ _id: id, isActive: true }).select("fullName role branch year interests createdAt"); if (!user) throw new HttpError(404, "User not found."); const [profile, skills] = await Promise.all([Profile.findOne({ user: id }), UserSkill.find({ user: id }).populate("skill", "name slug category")]); sendData(res, { user, profile, skills }); }));
router.put("/me", authenticate, validateBody(profileSchema), asyncHandler(async (req, res) => { const { fullName, branch, year, interests, ...profile } = req.body as z.infer<typeof profileSchema>; const user = await User.findByIdAndUpdate(req.user!.id, { ...(fullName && { fullName }), ...(branch && { branch }), ...(year && { year }), ...(interests && { interests }) }, { new: true, runValidators: true }); const updated = await Profile.findOneAndUpdate({ user: req.user!.id }, { $set: profile }, { new: true, upsert: true, runValidators: true }); sendData(res, { user, profile: updated }, "Profile updated."); }));
router.get("/me/notifications", authenticate, asyncHandler(async (req, res) => { const rows = await Notification.find({ user: req.user!.id }).sort({ createdAt: -1 }).limit(100); sendData(res, rows); }));
router.get("/me/skills", authenticate, asyncHandler(async (req, res) => { const rows = await UserSkill.find({ user: req.user!.id }).populate("skill"); sendData(res, rows); }));
router.post("/me/skills", authenticate, validateBody(z.object({ skillId: z.string().length(24), intent: z.enum(["know", "learn"]), level: z.enum(["beginner", "intermediate", "advanced", "expert"]).optional() })), asyncHandler(async (req, res) => { const body = req.body as { skillId: string; intent: "know"|"learn"; level?: string }; const skill = await Skill.findById(objectId(body.skillId)); if (!skill) throw new HttpError(404, "Skill not found."); const row = await UserSkill.findOneAndUpdate({ user: req.user!.id, skill: skill._id, intent: body.intent }, { $set: { level: body.level || "beginner" } }, { upsert: true, new: true, runValidators: true }).populate("skill"); sendData(res, row, "Skill added.", 201); }));
router.post("/:id/follow", authenticate, asyncHandler(async (req, res) => { await follow(req.user!.id, objectId(req.params.id)); sendData(res, {}, "Followed.", 201); }));
router.delete("/:id/follow", authenticate, asyncHandler(async (req, res) => { await Follow.deleteOne({ follower: req.user!.id, following: objectId(req.params.id) }); sendData(res, {}, "Unfollowed."); }));
async function follow(follower: string, following: string) { if (follower === following) throw new HttpError(400, "You cannot follow yourself."); if (!(await User.exists({ _id: following, isActive: true }))) throw new HttpError(404, "User not found."); await Follow.updateOne({ follower, following }, { $setOnInsert: { follower, following } }, { upsert: true }); await notify(following, "follow", "Someone followed you.", `/users/${follower}`); }
export { follow };
const skillsRouter = Router();
skillsRouter.get("/", asyncHandler(async (req, res) => { const filter = req.query.q ? { name: new RegExp(String(req.query.q).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") } : {}; sendData(res, await Skill.find(filter).sort({ name: 1 }).limit(100)); }));
skillsRouter.post("/", authenticate, allowRoles("creator", "admin"), validateBody(z.object({ name: z.string().trim().min(2).max(80), category: z.string().optional(), description: z.string().max(500).optional() })), asyncHandler(async (req, res) => { const { name, category, description } = req.body; const skill = await Skill.create({ name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), category, description }); sendData(res, skill, "Skill created.", 201); }));
skillsRouter.get("/matches", authenticate, asyncHandler(async (req, res) => { const wanted = await UserSkill.find({ user: req.user!.id, intent: "learn" }).distinct("skill"); const people = await UserSkill.find({ skill: { $in: wanted }, intent: "know", user: { $ne: req.user!.id } }).distinct("user"); const users = await User.find({ _id: { $in: people }, isActive: true }).select("fullName branch year role").limit(30); sendData(res, users, "Students who know skills you want to learn."); }));
export { skillsRouter };

export default router;

