import bcrypt from "bcrypt";
import { connectDatabase, disconnectDatabase } from "./config/database";
import { User, Profile, Skill, UserSkill, Category, Course, CourseModule, Lesson, Video, Note, Quiz, QuizQuestion, Comment, Rating, Review, Connection, Enrollment } from "./models";

async function run() {
  await connectDatabase();
  const passwordFor = async (email: string, password: string, role: "student" | "creator" | "admin", branch: string, year: number) => {
    const user = await User.findOneAndUpdate({ email }, { $set: { fullName: email.split("@")[0].replace(/\b\w/g, (c) => c.toUpperCase()), email, passwordHash: await bcrypt.hash(password, 12), role, branch, year, isActive: true } }, { upsert: true, new: true, runValidators: true });
    await Profile.updateOne({ user: user._id }, { $setOnInsert: { user: user._id, bio: "Learning and sharing at Prabhat Engineering College." } }, { upsert: true });
    return user;
  };
  const [student, creator, admin] = await Promise.all([passwordFor("student@example.com", "Student123!", "student", "Computer Science", 2), passwordFor("creator@example.com", "Creator123!", "creator", "Information Technology", 3), passwordFor("admin@example.com", "Admin123!", "admin", "Computer Science", 4)]);
  const categoryNames = ["Development", "Design", "Engineering", "Data Science", "Business"];
  const categories = await Promise.all(categoryNames.map((name) => Category.findOneAndUpdate({ name }, { $set: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-") }, $setOnInsert: { isActive: true } }, { upsert: true, new: true })));
  const skillNames = ["JavaScript", "React", "Python", "Figma", "CAD", "Data Analysis"];
  const skills = await Promise.all(skillNames.map((name) => Skill.findOneAndUpdate({ name }, { $set: { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-") } }, { upsert: true, new: true })));
  await Promise.all([UserSkill.updateOne({ user: student._id, skill: skills[0]._id, intent: "learn" }, { $setOnInsert: { user: student._id, skill: skills[0]._id, intent: "learn" } }, { upsert: true }), UserSkill.updateOne({ user: creator._id, skill: skills[0]._id, intent: "know" }, { $setOnInsert: { user: creator._id, skill: skills[0]._id, intent: "know", level: "advanced" } }, { upsert: true })]);
  const course = await Course.findOneAndUpdate({ title: "Build your first website with HTML & CSS" }, { $set: { title: "Build your first website with HTML & CSS", description: "A practical, peer-led introduction to building responsive pages with semantic HTML and modern CSS.", category: categories[0]._id, difficulty: "beginner", creator: creator._id, tags: ["HTML", "CSS", "JavaScript", "web development"], objectives: ["Build a semantic web page", "Style a responsive layout"], duration: 160, published: true, averageRating: 4.9, ratingCount: 1 } }, { upsert: true, new: true });
  const module = await CourseModule.findOneAndUpdate({ course: course._id, title: "Your first page" }, { $set: { course: course._id, title: "Your first page", position: 0 } }, { upsert: true, new: true });
  const lesson = await Lesson.findOneAndUpdate({ module: module._id, title: "Structure with HTML" }, { $set: { module: module._id, title: "Structure with HTML", content: "Use headings, paragraphs, links and semantic structure to create your first page.", position: 0, duration: 20 } }, { upsert: true, new: true });
  course.modules = [module._id]; await course.save();
  const video = await Video.findOneAndUpdate({ title: "A friendly introduction to React" }, { $set: { title: "A friendly introduction to React", description: "Learn components and props through a small example.", category: categories[0]._id, creator: creator._id, url: "https://example.com/demo-react-video", duration: 540, tags: ["React", "JavaScript"], published: true } }, { upsert: true, new: true });
  const note = await Note.findOneAndUpdate({ title: "HTML and CSS quick reference" }, { $set: { title: "HTML and CSS quick reference", description: "A concise peer-made reference for common HTML and CSS patterns.", category: categories[0]._id, creator: creator._id, content: "HTML structures content; CSS controls presentation. Prefer semantic elements and responsive layouts.", tags: ["HTML", "CSS"], published: true } }, { upsert: true, new: true });
  const quiz = await Quiz.findOneAndUpdate({ title: "HTML foundations check-in" }, { $set: { title: "HTML foundations check-in", description: "Check your understanding of semantic HTML.", course: course._id, creator: creator._id, passingScore: 60, published: true } }, { upsert: true, new: true });
  const question = await QuizQuestion.findOneAndUpdate({ quiz: quiz._id, prompt: "Which element is best for the main page heading?" }, { $set: { quiz: quiz._id, prompt: "Which element is best for the main page heading?", options: ["<h1>", "<div>", "<span>"], correctAnswer: 0, explanation: "Use h1 for the page's primary heading.", marks: 1 } }, { upsert: true, new: true });
  quiz.questions = [question._id]; await quiz.save();
  const comment = await Comment.findOneAndUpdate({ user: student._id, content: course._id, body: "Clear explanation and a great place to start." }, { $setOnInsert: { user: student._id, contentType: "Course", content: course._id, body: "Clear explanation and a great place to start." } }, { upsert: true, new: true });
  await Promise.all([Rating.updateOne({ user: student._id, contentType: "Course", content: course._id }, { $set: { user: student._id, contentType: "Course", content: course._id, value: 5 } }, { upsert: true }), Review.updateOne({ user: student._id, contentType: "Course", content: course._id }, { $set: { user: student._id, contentType: "Course", content: course._id, text: "A clear, useful first course.", rating: 5 } }, { upsert: true }), Enrollment.updateOne({ user: student._id, course: course._id }, { $setOnInsert: { user: student._id, course: course._id } }, { upsert: true }), Connection.updateOne({ requester: student._id, recipient: creator._id }, { $set: { status: "accepted" } }, { upsert: true })]);
  console.log(`Seed complete. Categories: ${categories.length}; skills: ${skills.length}; course: ${course._id}; video: ${video._id}; note: ${note._id}; lesson: ${lesson._id}; comment: ${comment._id}; admin: ${admin.email}`);
}
run().catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => disconnectDatabase());
