"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { authApi } from "@/src/lib/api";
export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const isSignup=mode==="signup";
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);const fd=new FormData(event.currentTarget);try{if(isSignup)await authApi.register({fullName:String(fd.get("fullName")),email:String(fd.get("email")),password:String(fd.get("password")),confirmPassword:String(fd.get("confirmPassword")),branch:String(fd.get("branch")),year:Number(fd.get("year"))});else await authApi.login(String(fd.get("email")),String(fd.get("password")));router.push("/profile");}catch(e){setError(e instanceof Error?e.message:"Could not complete sign in.");}finally{setBusy(false);}}
  return <main className="auth-page"><a className="auth-brand" href="/"><img src="/prabhatians-logo.svg" alt=""/><span>PRABHATIANS<small>Connect · Learn · Share</small></span></a><section className="auth-card"><span className="auth-eyebrow">PRABHAT ENGINEERING COLLEGE</span><h1>{isSignup?"Join your learning community":"Welcome back"}</h1><p>{isSignup?"Create your student account to connect, learn and share.":"Sign in to continue learning with your peers."}</p><form onSubmit={submit}>{isSignup&&<><label>Full name<input name="fullName" autoComplete="name" minLength={2} maxLength={100} required/></label><label>Branch<input name="branch" placeholder="e.g. Computer Science" required/></label><label>Year<select name="year" defaultValue="1" required><option value="1">1st year</option><option value="2">2nd year</option><option value="3">3rd year</option><option value="4">4th year</option></select></label></>}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={isSignup?"new-password":"current-password"} minLength={8} required/></label>{isSignup&&<label>Confirm password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={8} required/></label>}{error&&<div className="auth-error" role="alert">{error}</div>}<button disabled={busy}>{busy?"Please wait…":isSignup?"Create account":"Sign in"}<span>→</span></button></form><div className="auth-switch">{isSignup?"Already have an account? ":"New to PRABHATIANS? "}<a href={isSignup?"/login":"/signup"}>{isSignup?"Sign in":"Create an account"}</a></div></section><p className="auth-foot">Built with care at Prabhat Engineering College.</p></main>;
}
